import { describe, expect, test } from "bun:test";
import { mdToHtml } from "../src/report/markdown.ts";

describe("mdToHtml", () => {
  test("headings map to h2/h3", () => {
    expect(mdToHtml("## Executive summary")).toBe("<h2>Executive summary</h2>");
    expect(mdToHtml("### med - X")).toBe("<h3>med - X</h3>");
  });

  test("unordered + ordered lists", () => {
    expect(mdToHtml("- a\n- b")).toBe("<ul><li>a</li><li>b</li></ul>");
    expect(mdToHtml("1. first\n2. second")).toBe("<ol><li>first</li><li>second</li></ol>");
  });

  test("inline bold, code, and http links", () => {
    expect(mdToHtml("**bold** and `code`")).toBe(
      "<p><strong>bold</strong> and <code>code</code></p>",
    );
    expect(mdToHtml("see [docs](https://example.com/x)")).toBe(
      '<p>see <a href="https://example.com/x" rel="noreferrer">docs</a></p>',
    );
  });

  test("escapes HTML so model output cannot inject markup", () => {
    expect(mdToHtml("a <script>alert(1)</script> b")).toBe(
      "<p>a &lt;script&gt;alert(1)&lt;/script&gt; b</p>",
    );
  });

  test("non-http links are NOT turned into anchors", () => {
    expect(mdToHtml("[x](javascript:alert(1))")).toBe("<p>[x](javascript:alert(1))</p>");
  });

  test("fenced code block is escaped and wrapped in pre/code", () => {
    expect(mdToHtml("```\nSET x = <1>\n```")).toBe("<pre><code>SET x = &lt;1&gt;</code></pre>");
  });

  test("HTML comment (narrate provenance header) is dropped", () => {
    expect(mdToHtml("<!-- generated by sbperf -->\n\n## Summary")).toBe("<h2>Summary</h2>");
  });

  test("horizontal rule + paragraph joining", () => {
    expect(mdToHtml("line one\nline two\n\n---")).toBe("<p>line one line two</p>\n<hr>");
  });

  test("a realistic narrate block round-trips into structured HTML", () => {
    const md =
      "## Executive summary\nAll good. See [d](https://x.io).\n\n## Priorities\n1. Do a\n2. Do b\n\n### med - Cache\nRaise it.";
    const html = mdToHtml(md);
    expect(html).toContain("<h2>Executive summary</h2>");
    expect(html).toContain('<a href="https://x.io" rel="noreferrer">d</a>');
    expect(html).toContain("<ol><li>Do a</li><li>Do b</li></ol>");
    expect(html).toContain("<h3>med - Cache</h3>");
  });
});
