import { describe, expect, test } from "bun:test";
import {
  buildMessages,
  buildNarrativeInput,
  clientFromEnv,
  type LlmClient,
  type LlmMessage,
  narrate,
  OpenAiCompatClient,
} from "../src/narrate.ts";
import type { Analysis } from "../src/schemas.ts";

function base(): Analysis {
  return {
    meta: {
      ref: "r",
      name: "demo",
      region: "eu",
      status: "ACTIVE_HEALTHY",
      pgVersion: "17",
      createdAt: "x",
      collectedAt: "x",
      sbperfVersion: "t",
      sqlSource: "read-only",
    },
    health: [],
    disk: null,
    pgConfig: null,
    pooler: null,
    backups: null,
    upgrade: null,
    functions: [],
    functionStats: [],
    buckets: [],
    security: null,
    advisors: { performance: [], security: [] },
    apiCounts: [],
    sql: {
      dbSize: "1 GB",
      cacheHitPct: 92,
      indexHitPct: null,
      statsResetAge: null,
      pgSettings: [],
      topStatements: Array.from({ length: 20 }, (_, i) => ({
        query: `select * from t${i} where a=$1`,
        pct: 30 - i,
        calls: 100,
        mean_ms: 5,
      })),
      topByCalls: [],
      biggestTables: [{ schema: "public", table: "public.big", total_size: "500 MB" }],
      indexStats: [{ schema: "public", table: "public.x", index: "public.i", unused: true }],
      duplicateIndexes: [{ schema: "public", table: "public.x", indexes: "i1, i2", copies: 2 }],
      rlsUnindexed: [{ schema: "public", table: "public.docs", column: "owner_id" }],
      seqScanHeavy: [],
      bloat: [],
      trafficProfile: [],
      deadTuples: [],
      txidWraparound: [],
      replicationSlots: [],
      rlsPolicies: [],
      connections: [{ state: "active", connections: 3 }],
      roleStats: [],
      longRunning: [],
      locks: [],
      blocking: [],
      storageUsage: [],
      extensions: [],
      unindexedVectors: [],
    },
    metrics: { available: false, samples: [] },
    trends: [{ title: "CPU utilization (%)", unit: "%", points: [{ t: 1, v: 42 }] }],
    sync: null,
    narrative: null,
    errors: [],
  };
}

describe("buildNarrativeInput", () => {
  test("includes findings with remediation + doc, and bounds the evidence", () => {
    const input = buildNarrativeInput(base());
    expect(Array.isArray(input.findings)).toBe(true);
    const cache = input.findings.find((f) => f.title.includes("Cache hit ratio 92%"));
    expect(cache?.remediation).toBeTruthy();
    expect(cache?.doc).toContain("http");
    // outliers capped at 8 even though 20 were provided
    expect(input.evidence.queryOutliers).toHaveLength(8);
    expect(input.evidence.duplicateIndexes).toBe(1);
    expect(input.evidence.rlsUnindexedColumns).toEqual(["public.docs.owner_id"]);
    // enriched trend shape so the model reasons over the trajectory, not just latest
    expect(input.trends[0]).toMatchObject({
      title: "CPU utilization (%)",
      latest: 42,
      mean: 42,
      sufficient: false, // single point -> not trustworthy for trend claims
    });
    expect(input.trends[0]).toHaveProperty("direction");
    expect(input.trends[0]).toHaveProperty("perDay");
  });

  test("flags degraded collection so the model can caveat", () => {
    const a = base();
    a.meta.status = "INACTIVE";
    expect(buildNarrativeInput(a).degraded).toBe(true);
  });

  test("no-PAT mode: unknown status is NOT degraded; managementApi flagged", () => {
    const a = base();
    a.meta.managementApi = false;
    a.meta.status = "unknown";
    const input = buildNarrativeInput(a);
    expect(input.degraded).toBe(false); // unknown status in no-PAT != degraded
    expect(input.project.managementApi).toBe(false);
  });
});

describe("buildMessages", () => {
  test("system rule + user payload with the JSON embedded", () => {
    const msgs = buildMessages(base());
    expect(msgs[0]?.role).toBe("system");
    expect(msgs[0]?.content).toContain("Do NOT invent");
    expect(msgs[1]?.role).toBe("user");
    expect(msgs[1]?.content).toContain("```json");
    expect(msgs[1]?.content).toContain("demo");
  });
});

describe("narrate", () => {
  test("prepends a provenance header and returns the model text", async () => {
    const fake: LlmClient = {
      model: "fake-1",
      complete: async (_m: LlmMessage[]) => "## Executive summary\nAll good.",
    };
    const out = await narrate(base(), fake);
    expect(out).toContain("generated by sbperf narrate (fake-1)");
    expect(out).toContain("## Executive summary");
  });

  test("throws on an empty completion", async () => {
    const fake: LlmClient = { model: "x", complete: async () => "   " };
    await expect(narrate(base(), fake)).rejects.toThrow(/empty/);
  });
});

describe("OpenAiCompatClient", () => {
  test("posts chat/completions with auth + model and parses the content", async () => {
    let seenUrl = "";
    let seenBodyRaw = "";
    let seenAuth = "";
    const fetchImpl = (async (url: string, init: RequestInit) => {
      seenUrl = url;
      seenBodyRaw = init.body as string;
      seenAuth = (init.headers as Record<string, string>).authorization ?? "";
      return new Response(JSON.stringify({ choices: [{ message: { content: "hi" } }] }), {
        status: 200,
      });
    }) as unknown as typeof fetch;
    const c = new OpenAiCompatClient("https://api.example.com/v1/", "m1", "sk-x", fetchImpl);
    const out = await c.complete([{ role: "user", content: "q" }]);
    expect(out).toBe("hi");
    expect(seenUrl).toBe("https://api.example.com/v1/chat/completions");
    expect(JSON.parse(seenBodyRaw).model).toBe("m1");
    expect(seenAuth).toBe("Bearer sk-x");
  });

  test("throws on non-2xx", async () => {
    const fetchImpl = (async () =>
      new Response("nope", { status: 500 })) as unknown as typeof fetch;
    const c = new OpenAiCompatClient("http://x/v1", "m", undefined, fetchImpl);
    await expect(c.complete([])).rejects.toThrow(/500/);
  });
});

describe("clientFromEnv", () => {
  test("errors clearly when unconfigured", () => {
    const r = clientFromEnv({});
    expect("error" in r && r.error).toContain("SBPERF_LLM_BASE_URL");
  });
  test("builds a client when base url + model are set", () => {
    const r = clientFromEnv({ SBPERF_LLM_BASE_URL: "http://x/v1", SBPERF_LLM_MODEL: "m" });
    expect("client" in r && r.client.model).toBe("m");
  });
});
