import { mkdir } from "node:fs/promises";
import { join } from "node:path";
import type { TransportConfig } from "./config.ts";
import { Management } from "./management.ts";
import { makeTransport } from "./transport.ts";

/**
 * Generate a ready-to-run Prometheus + Grafana stack that scrapes the project
 * metrics endpoint on an interval, giving true going-forward time-series
 * history (the metrics endpoint itself is only point-in-time). The generated
 * dir contains real credentials in prometheus.yml, so it is gitignored.
 */
export async function writeScraper(
  ref: string,
  config: TransportConfig,
  dir: string,
): Promise<string> {
  const scrape = await buildScrapeJob(ref, config);

  const prometheusYml = `# Generated by sbperf for project ${ref}. Contains a credential - do not commit.
global:
  scrape_interval: 60s
  scrape_timeout: 30s

scrape_configs:
  - job_name: supabase
    scheme: ${scrape.scheme}
    metrics_path: ${scrape.metricsPath}
${scrape.authBlock}
    static_configs:
      - targets: ['${scrape.target}']
`;

  const composeYml = `# Generated by sbperf. Prometheus scrapes the Supabase metrics endpoint;
# Grafana visualises it with 90-day retention for the 30-day dashboard views.
services:
  prometheus:
    image: prom/prometheus:v3.1.0
    restart: unless-stopped
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.retention.time=90d
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./data/prometheus:/prometheus
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:11.4.0
    restart: unless-stopped
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: Viewer
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
      - ./data/grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
`;

  const datasourceYml = `apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
`;

  const dashProviderYml = `apiVersion: 1
providers:
  - name: sbperf
    type: file
    options:
      path: /var/lib/grafana/dashboards
`;

  await mkdir(join(dir, "grafana/provisioning/datasources"), { recursive: true });
  await mkdir(join(dir, "grafana/provisioning/dashboards"), { recursive: true });
  await mkdir(join(dir, "grafana/dashboards"), { recursive: true });
  await mkdir(join(dir, "data"), { recursive: true });

  await Promise.all([
    Bun.write(join(dir, "prometheus.yml"), prometheusYml),
    Bun.write(join(dir, "compose.yml"), composeYml),
    Bun.write(join(dir, "grafana/provisioning/datasources/prometheus.yml"), datasourceYml),
    Bun.write(join(dir, "grafana/provisioning/dashboards/dashboards.yml"), dashProviderYml),
    Bun.write(
      join(dir, "grafana/dashboards/supabase.json"),
      JSON.stringify(dashboard(ref), null, 2),
    ),
    Bun.write(join(dir, ".gitignore"), "prometheus.yml\ndata/\n"),
    Bun.write(join(dir, "README.md"), scraperReadme(ref)),
  ]);

  return dir;
}

type ScrapeJob = { scheme: string; metricsPath: string; target: string; authBlock: string };

async function buildScrapeJob(ref: string, config: TransportConfig): Promise<ScrapeJob> {
  if (config.kind === "gatekeeper") {
    const u = new URL(config.baseUrl);
    return {
      scheme: u.protocol.replace(":", ""),
      metricsPath: `/supabase/metrics/${ref}`,
      target: u.host,
      authBlock: `    authorization:\n      credentials: ${config.key}`,
    };
  }
  // direct: fetch the service_role key to embed as basic-auth password.
  const m = new Management(makeTransport(config));
  const keys = await m.apiKeys(ref);
  const sr = keys.find((k) => k.name === "service_role")?.api_key;
  if (!sr) throw new Error(`no service_role key for ${ref}`);
  return {
    scheme: "https",
    metricsPath: "/customer/v1/privileged/metrics",
    target: `${ref}.supabase.co`,
    authBlock: `    basic_auth:\n      username: service_role\n      password: ${sr}`,
  };
}

function panel(id: number, title: string, expr: string, x: number, y: number): unknown {
  return {
    id,
    title,
    type: "timeseries",
    datasource: { type: "prometheus", uid: "prometheus" },
    gridPos: { h: 8, w: 12, x, y },
    targets: [{ expr, refId: "A" }],
  };
}

function dashboard(ref: string): unknown {
  return {
    title: `Supabase - ${ref}`,
    uid: `sbperf-${ref}`.slice(0, 40),
    tags: ["sbperf"],
    time: { from: "now-30d", to: "now" },
    refresh: "5m",
    schemaVersion: 39,
    panels: [
      panel(1, "CPU load (1m)", "node_load1", 0, 0),
      panel(2, "Memory available", "node_memory_MemAvailable_bytes", 12, 0),
      panel(3, "DB connections", "pg_stat_database_num_backends", 0, 8),
      panel(4, "Pooler client conns (active/waiting)", "pgbouncer_pools_cl_active", 12, 8),
      panel(5, "Disk free bytes", 'node_filesystem_avail_bytes{mountpoint="/data"}', 0, 16),
      panel(6, "Deadlocks", "pg_stat_database_deadlocks", 12, 16),
    ],
  };
}

function scraperReadme(ref: string): string {
  return `# sbperf metrics scraper - ${ref}

Prometheus scrapes the Supabase metrics endpoint every 60s; Grafana visualises
it with 90-day retention so the 30-day dashboard views fill in over time.

    docker compose up -d

- Grafana: http://localhost:3000 (anonymous viewer; admin/admin to edit)
- Prometheus: http://localhost:9090

\`prometheus.yml\` contains a live credential and is gitignored. History only
accumulates from the moment you start scraping - it is not retroactive.
`;
}
